In [120]:
x = 5
print('x =', x)

x = 5


In [121]:
x = x + 0.5
x

5.5

In [122]:
y = 5

In [123]:
z = y + 5
z

10

In [124]:
if z < 5:
    print(y)
    z = z + y
#thoát ra khỏi lệnh if
print(z)

10


In [125]:
import numpy as np
#Tạo danh sách mảng bắt đầu từ start đến stop
a = np.arange(0, 10, 1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
myTuple = ('abc', np.arange(0,10,0.2), 2.5)

In [127]:
myTuple[0]

'abc'

In [128]:
myTuple[1]

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [129]:
myTuple[2]

2.5

In [130]:
#Tạo dataframe
import numpy as np
import pandas as pd

t = np.arange(0, 100, 0.1)
x = np.sin(t)
y = np.cos(t)
#'Tên_cột':giá_Trị
dframe = pd.DataFrame({'Time': t, 'x': x, 'y': y})
dframe

Time         x         y
0     0.0  0.000000  1.000000
1     0.1  0.099833  0.995004
2     0.2  0.198669  0.980067
3     0.3  0.295520  0.955336
4     0.4  0.389418  0.921061
..    ...       ...       ...
995  99.5 -0.857795  0.513991
996  99.6 -0.802196  0.597060
997  99.7 -0.738582  0.674163
998  99.8 -0.667588  0.744531
999  99.9 -0.589924  0.807459

[1000 rows x 3 columns]

In [131]:
dframe.head(3) #mặc định 5 dòng đầu
#dframe.head(3) #xuất 3 dòng đầu tiên
#dframe.tail() #xuất 5 dòng cuối cùng

Time         x         y
0   0.0  0.000000  1.000000
1   0.1  0.099833  0.995004
2   0.2  0.198669  0.980067

In [132]:
dframe[3:6] #in ra các dòng từ start đến stop - 1

Time         x         y
3   0.3  0.295520  0.955336
4   0.4  0.389418  0.921061
5   0.5  0.479426  0.877583

In [133]:
# dframe['Time']
#Cách 2. dframe.Time
dframe['Time'][3:4]
#mảng nằm trong [gt1, gt2]
dframe[['Time', 'x']]
dframe[['Time', 'x']].tail()
dframe[['Time', 'x']][3:6]

Time         x
3   0.3  0.295520
4   0.4  0.389418
5   0.5  0.479426

In [137]:
#Đọc dữ liệu từ file .txt
data = pd.read_csv('babies.txt', delim_whitespace=True)
dframe = data[['bwt','smoke']]
dframe
dframe.head()
dframe[3:7]

#Lọc các dòng có cột smoke = 1
dframe_cohutThuoc = data[data['smoke'] == 1]
dframe_cohutThuoc

C:\Users\HungNguyen\AppData\Local\Temp\ipykernel_6724\734741097.py:2: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv('babies.txt', delim_whitespace=True)


bwt  smoke
2     128      1
4     108      1
9     143      1
11    144      1
12    141      1
...   ...    ...
1224  143      1
1225  113      1
1226  109      1
1227  103      1
1233  130      1

[484 rows x 2 columns]

In [138]:
#Lọc các dòng có cột smoke = 0
dframe_khonghutThuoc = data[data['smoke'] == 0]
dframe_khonghutThuoc

bwt  smoke
0     120      0
1     113      0
3     123      0
5     136      0
6     138      0
...   ...    ...
1230  132      0
1231  113      0
1232  128      0
1234  125      0
1235  117      0

[742 rows x 2 columns]

In [139]:
#Lọc các dòng có cột smoke = 1
dframe_cohutThuoc = data[data['smoke'] == 1]
#Tạo mảng lấy dữ liệu cột bwt của dframe_cohutThuoc
arr_cohutThuoc = dframe_cohutThuoc['bwt'].to_numpy()
arr_cohutThuoc

array([128, 108, 143, 144, 141, 110,  92, 115, 119, 115, 103, 114, 114,
       134, 122, 138,  87, 143, 145, 108, 124, 122, 101, 128, 104, 137,
       103, 133,  91, 153,  99, 114, 129, 125, 114,  85,  87, 120, 107,
       119, 103,  91,  95, 141, 100, 115,  94, 101, 112, 128,  93, 100,
       105, 160, 113, 129, 118, 133, 116, 113, 131, 121, 122, 101, 113,
       131,  96, 142,  75, 125, 104, 118,  98, 150, 119, 101, 113,  97,
       115, 121, 117, 110, 130, 140, 111, 154, 122, 144, 114, 111, 154,
       150,  99, 117, 130,  81, 124, 125, 115, 104, 119, 123, 141, 129,
       119, 109, 104, 110,  98, 136, 121,  91,  85, 106, 109,  98, 101,
        71, 124,  93, 101, 100, 104, 117, 117, 117, 109, 120, 103, 123,
       104, 122, 116, 129, 133, 122, 133, 130, 106, 121, 140, 120, 127,
        71, 107, 129, 145, 102, 129, 135, 104, 126, 127,  98, 131,  99,
       115, 102, 143,  87, 130, 123, 116, 144, 120, 116, 112, 132, 146,
       119, 100, 118, 129, 122, 117, 144, 115,  99,  68, 102, 10

In [140]:
#Lọc các dòng có cột smoke = 0
dframe_khonghutThuoc = data[data['smoke'] == 0]
#Tạo mảng lấy dữ liệu cột bwt của dframe_khonghutThuoc
arr_khonghutThuoc = dframe_khonghutThuoc['bwt'].to_numpy()
arr_khonghutThuoc

array([120, 113, 123, 136, 138, 132, 120, 140, 114, 115, 144, 105, 137,
       122, 131, 146, 125, 122,  93, 130, 119, 113, 134, 107, 128, 129,
       110, 111, 155, 110, 122, 115, 102, 143, 146, 124, 145, 106,  75,
       107, 124,  97, 142, 130, 156, 120, 127, 121, 120, 149, 129, 139,
       138, 138, 131, 128, 134, 114,  92, 135, 125, 128, 105, 119, 116,
       133, 155, 126, 129, 137, 125, 134, 118, 131, 121, 131, 118, 152,
       121, 117, 112, 109, 132, 117, 128, 117, 134, 127, 122, 147, 120,
       144, 136, 102, 126, 126, 115, 127, 119, 123, 105, 134, 144, 111,
       125, 135, 134, 129, 121, 138, 136, 120, 134, 112, 132, 136,  96,
       124, 113, 137, 133, 107, 136, 130,  90, 123, 137, 101, 142, 124,
       151, 109, 131, 127, 117, 150,  85, 128, 105, 107, 119, 134, 117,
       115,  93, 125,  93, 129, 126,  85, 173, 111, 126, 122, 141, 142,
       113, 149, 128, 125, 114, 116, 125, 110, 138, 142, 102, 140, 133,
       127, 152, 143, 131, 113, 131, 148, 137, 117, 115, 132, 11

In [144]:
import pandas as pd
import numpy as np
data = pd.read_excel('18_M&M.xls')
print(data)


      Red  Orange  Yellow  Brown   Blue  Green
0   0.751   0.735   0.883  0.696  0.881  0.925
1   0.841   0.895   0.769  0.876  0.863  0.914
2   0.856   0.865   0.859  0.855  0.775  0.881
3   0.799   0.864   0.784  0.806  0.854  0.865
4   0.966   0.852   0.824  0.840  0.810  0.865
5   0.859   0.866   0.858  0.868  0.858  1.015
6   0.857   0.859   0.848  0.859  0.818  0.876
7   0.942   0.838   0.851  0.982  0.868  0.809
8   0.873   0.863     NaN    NaN  0.803  0.865
9   0.809   0.888     NaN    NaN  0.932  0.848
10  0.890   0.925     NaN    NaN  0.842  0.940
11  0.878   0.793     NaN    NaN  0.832  0.833
12  0.905   0.977     NaN    NaN  0.807  0.845
13    NaN   0.850     NaN    NaN  0.841  0.852
14    NaN   0.830     NaN    NaN  0.932  0.778
15    NaN   0.856     NaN    NaN  0.833  0.814
16    NaN   0.842     NaN    NaN  0.881  0.791
17    NaN   0.778     NaN    NaN  0.818  0.810
18    NaN   0.786     NaN    NaN  0.864  0.881
19    NaN   0.853     NaN    NaN  0.825    NaN
20    NaN   0